### ISSUE TITLE
Clear still might crash the server.

### ISSUE THREAD

**Issue by SBPrime** [WorldCretornica/PlotMe-DefaultGenerator#7]
Hi there,
First of all I would like to congratulate you on finally making the clear operation work in package mode. While looking at your code I noticed that the packaging is done by limiting the number of blocks changed. By experience I know that this wont always solve the TPS drop issue (I had a similar problem in AsyncWorldEdit). Placing a block that causes light changing takes much more time. Therefore I suggest you add an additional stop criteria based on time spend on placing blocks.

**Comment by MattBDev** [comment]
@SBPrime Do you have an example from your code that does what you are describing so I have a better idea on how to go about resolving this?

**Comment by SBPrime** [comment]
This fragment of code makes sure that a function will exit when maximum changes are done or allowed processing time runs out:
https://github.com/SBPrime/AsyncWorldEdit/blob/master/AsyncWorldEdit/src/org/primesoft/asyncworldedit/blockPlacer/BlockPlacer.java#L291-L320
