### ISSUE TITLE
Internal Exception on generation of world with MV

### ISSUE THREAD

**Issue by Phykick** [WorldCretornica/PlotMe-DefaultGenerator#8]
Running spigot-1.8 with multiverse, /mv create Creative normal -g PlotMe-DefaultGenerator throws an error. ( Could not pass event WorldLoadEvent to Multiverse-Core v2.5-b692 )
Full startup log: http://pastebin.com/eu4M94Mg
I will post a list of plugins if neccesary, but there are alot.

**Comment by MattBDev** [comment]
Thats the result of not having the world in your default generator config or plotme config.
