### ISSUE TITLE
PlotMe-Default Generator fails to create new world

### ISSUE THREAD

**Issue by AustinTX1985** [WorldCretornica/PlotMe-DefaultGenerator#9]
When attempting to create a plot world using PlotMe and the PlotMe-Default Generator in conjunction with Multiverse, I get a several line error in the console that ends up pointing to a NulPointerException in the generateExtBlockSections part of the plugin. Here is a pastebin of the entire error: http://pastebin.com/fjRa1Rzc. Any help will be greatly appreciated as we are really wanting to create a plot world for our players to be able to use. Thanks for your time.

**Comment by MattBDev** [comment]
Please setup your configurations properly based off of the examples on the website.

**Comment by AustinTX1985** [comment]
The configurations ARE properly based off of the examples on your website. I even went so far as to copy/paste them into the plugin config.yml, yet I still am unable to create a plot world. This is clearly not an invalid issue, but a legitimate bug. I would prefer to use this plugin but if I am unable to get it to work, I will have to find another. Here is the most recent server crash that resulted AFTER updating the config: http://pastebin.com/RiLzPuxh.

**Comment by MattBDev** [comment]
Can you show me the config files?

**Comment by AustinTX1985** [comment]
PlotMe Config: http://pastebin.com/YdbfT4nN
PlotMe-Default Generator Config: http://pastebin.com/fFgspjAi

**Comment by MattBDev** [comment]
Remove the "CreativePlots" but leave the "creativeplots" in the generator config and test it

**Comment by AustinTX1985** [comment]
That worked. Apparently using any capitalization when creating the world causes it to not work. Thanks for your willingness to work with me. You can add DivineCraft to the list of servers using this plugin. Thanks again!

**Comment by GotzM** [comment]
i need help im having almost the same problem but mine is still creating a normal world with seeds..... i dont know what to do
